[package]
name = "dsmc"
version = "0.11.0"
edition = "2024"
license = "MIT"
authors = ["Digitalservo"]
description = "Digitalservo Motion Control Library"
readme = "README.md"
documentation = "https://docs.rs/dsmc"
homepage = "https://github.com/DigitalServo/DigitalServo-Motion-Control-Library"
repository = "https://github.com/DigitalServo/DigitalServo-Motion-Control-Library"

[dependencies]
csv = "1.4.0"
nalgebra = "0.35.0"
num-complex = { version = "0.4.6", features = ["serde"] }
num-traits = "0.2.19"
rustfft = "6.4.1"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
